-- questions 테이블 생명과학 정답 및 단원 업데이트
-- id 312 = 문제 1번, id 758 = 문제 447번
-- Supabase SQL Editor에서 실행하세요

-- 생명과학 데이터 업데이트 (id 312~758, 문제번호 1~447)

-- [생물의 특성과 물질대사] 문제 1-60 (id 312-371)
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '5' WHERE id = 312;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '1' WHERE id = 313;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '2' WHERE id = 314;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '5' WHERE id = 315;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '3' WHERE id = 316;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '2' WHERE id = 317;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '5' WHERE id = 318;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '2' WHERE id = 319;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '2' WHERE id = 320;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '5' WHERE id = 321;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '2' WHERE id = 322;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '5' WHERE id = 323;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '4' WHERE id = 324;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '5' WHERE id = 325;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '1' WHERE id = 326;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '4' WHERE id = 327;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '5' WHERE id = 328;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '4' WHERE id = 329;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '2' WHERE id = 330;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '3' WHERE id = 331;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '3' WHERE id = 332;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '4' WHERE id = 333;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '2' WHERE id = 334;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '4' WHERE id = 335;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '5' WHERE id = 336;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '3' WHERE id = 337;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '1' WHERE id = 338;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '4' WHERE id = 339;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '2' WHERE id = 340;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '2' WHERE id = 341;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '3' WHERE id = 342;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '3' WHERE id = 343;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '4' WHERE id = 344;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '3' WHERE id = 345;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '3' WHERE id = 346;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '4' WHERE id = 347;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '5' WHERE id = 348;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '3' WHERE id = 349;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '5' WHERE id = 350;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '4' WHERE id = 351;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '2' WHERE id = 352;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '4' WHERE id = 353;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '1' WHERE id = 354;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '3' WHERE id = 355;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '5' WHERE id = 356;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '1' WHERE id = 357;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '5' WHERE id = 358;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '2' WHERE id = 359;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '3' WHERE id = 360;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '3' WHERE id = 361;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '4' WHERE id = 362;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '1' WHERE id = 363;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '1' WHERE id = 364;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '1' WHERE id = 365;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '1' WHERE id = 366;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '4' WHERE id = 367;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '2' WHERE id = 368;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '1' WHERE id = 369;
UPDATE questions SET unit = '생물의 특성과 물질대사', answer = '4' WHERE id = 370;

-- [기관계 통합적 작용] 문제 61-118 (id 372-429)
UPDATE questions SET unit = '기관계 통합적 작용', answer = '5' WHERE id = 372;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '4' WHERE id = 373;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '5' WHERE id = 374;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '1' WHERE id = 375;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '2' WHERE id = 376;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '2' WHERE id = 377;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '4' WHERE id = 378;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '3' WHERE id = 379;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '4' WHERE id = 380;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '4' WHERE id = 381;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '1' WHERE id = 382;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '3' WHERE id = 383;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '2' WHERE id = 384;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '4' WHERE id = 385;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '3' WHERE id = 386;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '4' WHERE id = 387;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '4' WHERE id = 388;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '2' WHERE id = 389;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '1' WHERE id = 390;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '4' WHERE id = 391;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '2' WHERE id = 392;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '2' WHERE id = 393;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '4' WHERE id = 394;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '4' WHERE id = 395;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '2' WHERE id = 396;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '4' WHERE id = 397;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '2' WHERE id = 398;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '1' WHERE id = 399;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '2' WHERE id = 400;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '2' WHERE id = 401;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '5' WHERE id = 402;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '5' WHERE id = 403;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '2' WHERE id = 404;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '5' WHERE id = 405;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '5' WHERE id = 406;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '3' WHERE id = 407;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '5' WHERE id = 408;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '5' WHERE id = 409;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '2' WHERE id = 410;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '5' WHERE id = 411;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '3' WHERE id = 412;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '1' WHERE id = 413;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '5' WHERE id = 414;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '2' WHERE id = 415;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '4' WHERE id = 416;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '1' WHERE id = 417;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '5' WHERE id = 418;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '5' WHERE id = 419;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '4' WHERE id = 420;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '2' WHERE id = 421;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '4' WHERE id = 422;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '4' WHERE id = 423;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '3' WHERE id = 424;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '3' WHERE id = 425;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '1' WHERE id = 426;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '4' WHERE id = 427;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '3' WHERE id = 428;
UPDATE questions SET unit = '기관계 통합적 작용', answer = '2' WHERE id = 429;

-- [자극의 전달] 문제 119-180 (id 430-491)
UPDATE questions SET unit = '자극의 전달', answer = '1' WHERE id = 430;
UPDATE questions SET unit = '자극의 전달', answer = '2' WHERE id = 431;
UPDATE questions SET unit = '자극의 전달', answer = '3' WHERE id = 432;
UPDATE questions SET unit = '자극의 전달', answer = '3' WHERE id = 433;
UPDATE questions SET unit = '자극의 전달', answer = '5' WHERE id = 434;
UPDATE questions SET unit = '자극의 전달', answer = '2' WHERE id = 435;
UPDATE questions SET unit = '자극의 전달', answer = '3' WHERE id = 436;
UPDATE questions SET unit = '자극의 전달', answer = '2' WHERE id = 437;
UPDATE questions SET unit = '자극의 전달', answer = '5' WHERE id = 438;
UPDATE questions SET unit = '자극의 전달', answer = '3' WHERE id = 439;
UPDATE questions SET unit = '자극의 전달', answer = '2' WHERE id = 440;
UPDATE questions SET unit = '자극의 전달', answer = '1' WHERE id = 441;
UPDATE questions SET unit = '자극의 전달', answer = '5' WHERE id = 442;
UPDATE questions SET unit = '자극의 전달', answer = '2' WHERE id = 443;
UPDATE questions SET unit = '자극의 전달', answer = '1' WHERE id = 444;
UPDATE questions SET unit = '자극의 전달', answer = '2' WHERE id = 445;
UPDATE questions SET unit = '자극의 전달', answer = '3' WHERE id = 446;
UPDATE questions SET unit = '자극의 전달', answer = '3' WHERE id = 447;
UPDATE questions SET unit = '자극의 전달', answer = '1' WHERE id = 448;
UPDATE questions SET unit = '자극의 전달', answer = '2' WHERE id = 449;
UPDATE questions SET unit = '자극의 전달', answer = '5' WHERE id = 450;
UPDATE questions SET unit = '자극의 전달', answer = '4' WHERE id = 451;
UPDATE questions SET unit = '자극의 전달', answer = '3' WHERE id = 452;
UPDATE questions SET unit = '자극의 전달', answer = '1' WHERE id = 453;
UPDATE questions SET unit = '자극의 전달', answer = '4' WHERE id = 454;
UPDATE questions SET unit = '자극의 전달', answer = '1' WHERE id = 455;
UPDATE questions SET unit = '자극의 전달', answer = '3' WHERE id = 456;
UPDATE questions SET unit = '자극의 전달', answer = '1' WHERE id = 457;
UPDATE questions SET unit = '자극의 전달', answer = '5' WHERE id = 458;
UPDATE questions SET unit = '자극의 전달', answer = '4' WHERE id = 459;
UPDATE questions SET unit = '자극의 전달', answer = '2' WHERE id = 460;
UPDATE questions SET unit = '자극의 전달', answer = '1' WHERE id = 461;
UPDATE questions SET unit = '자극의 전달', answer = '1' WHERE id = 462;
UPDATE questions SET unit = '자극의 전달', answer = '1' WHERE id = 463;
UPDATE questions SET unit = '자극의 전달', answer = '5' WHERE id = 464;
UPDATE questions SET unit = '자극의 전달', answer = '5' WHERE id = 465;
UPDATE questions SET unit = '자극의 전달', answer = '4' WHERE id = 466;
UPDATE questions SET unit = '자극의 전달', answer = '1' WHERE id = 467;
UPDATE questions SET unit = '자극의 전달', answer = '5' WHERE id = 468;
UPDATE questions SET unit = '자극의 전달', answer = '5' WHERE id = 469;
UPDATE questions SET unit = '자극의 전달', answer = '3' WHERE id = 470;
UPDATE questions SET unit = '자극의 전달', answer = '2' WHERE id = 471;
UPDATE questions SET unit = '자극의 전달', answer = '2' WHERE id = 472;
UPDATE questions SET unit = '자극의 전달', answer = '1' WHERE id = 473;
UPDATE questions SET unit = '자극의 전달', answer = '3' WHERE id = 474;
UPDATE questions SET unit = '자극의 전달', answer = '1' WHERE id = 475;
UPDATE questions SET unit = '자극의 전달', answer = '5' WHERE id = 476;
UPDATE questions SET unit = '자극의 전달', answer = '4' WHERE id = 477;
UPDATE questions SET unit = '자극의 전달', answer = '1' WHERE id = 478;
UPDATE questions SET unit = '자극의 전달', answer = '5' WHERE id = 479;
UPDATE questions SET unit = '자극의 전달', answer = '3' WHERE id = 480;
UPDATE questions SET unit = '자극의 전달', answer = '3' WHERE id = 481;
UPDATE questions SET unit = '자극의 전달', answer = '1' WHERE id = 482;
UPDATE questions SET unit = '자극의 전달', answer = '2' WHERE id = 483;
UPDATE questions SET unit = '자극의 전달', answer = '3' WHERE id = 484;
UPDATE questions SET unit = '자극의 전달', answer = '3' WHERE id = 485;
UPDATE questions SET unit = '자극의 전달', answer = '5' WHERE id = 486;
UPDATE questions SET unit = '자극의 전달', answer = '4' WHERE id = 487;
UPDATE questions SET unit = '자극의 전달', answer = '1' WHERE id = 488;
UPDATE questions SET unit = '자극의 전달', answer = '2' WHERE id = 489;
UPDATE questions SET unit = '자극의 전달', answer = '1' WHERE id = 490;
UPDATE questions SET unit = '자극의 전달', answer = '2' WHERE id = 491;

-- [신경계] 문제 181-240 (id 492-551)
UPDATE questions SET unit = '신경계', answer = '5' WHERE id = 492;
UPDATE questions SET unit = '신경계', answer = '4' WHERE id = 493;
UPDATE questions SET unit = '신경계', answer = '5' WHERE id = 494;
UPDATE questions SET unit = '신경계', answer = '3' WHERE id = 495;
UPDATE questions SET unit = '신경계', answer = '5' WHERE id = 496;
UPDATE questions SET unit = '신경계', answer = '4' WHERE id = 497;
UPDATE questions SET unit = '신경계', answer = '3' WHERE id = 498;
UPDATE questions SET unit = '신경계', answer = '3' WHERE id = 499;
UPDATE questions SET unit = '신경계', answer = '1' WHERE id = 500;
UPDATE questions SET unit = '신경계', answer = '4' WHERE id = 501;
UPDATE questions SET unit = '신경계', answer = '1' WHERE id = 502;
UPDATE questions SET unit = '신경계', answer = '4' WHERE id = 503;
UPDATE questions SET unit = '신경계', answer = '1' WHERE id = 504;
UPDATE questions SET unit = '신경계', answer = '5' WHERE id = 505;
UPDATE questions SET unit = '신경계', answer = '1' WHERE id = 506;
UPDATE questions SET unit = '신경계', answer = '5' WHERE id = 507;
UPDATE questions SET unit = '신경계', answer = '3' WHERE id = 508;
UPDATE questions SET unit = '신경계', answer = '5' WHERE id = 509;
UPDATE questions SET unit = '신경계', answer = '5' WHERE id = 510;
UPDATE questions SET unit = '신경계', answer = '2' WHERE id = 511;
UPDATE questions SET unit = '신경계', answer = '3' WHERE id = 512;
UPDATE questions SET unit = '신경계', answer = '4' WHERE id = 513;
UPDATE questions SET unit = '신경계', answer = '4' WHERE id = 514;
UPDATE questions SET unit = '신경계', answer = '3' WHERE id = 515;
UPDATE questions SET unit = '신경계', answer = '5' WHERE id = 516;
UPDATE questions SET unit = '신경계', answer = '5' WHERE id = 517;
UPDATE questions SET unit = '신경계', answer = '3' WHERE id = 518;
UPDATE questions SET unit = '신경계', answer = '3' WHERE id = 519;
UPDATE questions SET unit = '신경계', answer = '4' WHERE id = 520;
UPDATE questions SET unit = '신경계', answer = '5' WHERE id = 521;
UPDATE questions SET unit = '신경계', answer = '2' WHERE id = 522;
UPDATE questions SET unit = '신경계', answer = '2' WHERE id = 523;
UPDATE questions SET unit = '신경계', answer = '5' WHERE id = 524;
UPDATE questions SET unit = '신경계', answer = '3' WHERE id = 525;
UPDATE questions SET unit = '신경계', answer = '3' WHERE id = 526;
UPDATE questions SET unit = '신경계', answer = '4' WHERE id = 527;
UPDATE questions SET unit = '신경계', answer = '5' WHERE id = 528;
UPDATE questions SET unit = '신경계', answer = '3' WHERE id = 529;
UPDATE questions SET unit = '신경계', answer = '1' WHERE id = 530;
UPDATE questions SET unit = '신경계', answer = '2' WHERE id = 531;
UPDATE questions SET unit = '신경계', answer = '5' WHERE id = 532;
UPDATE questions SET unit = '신경계', answer = '1' WHERE id = 533;
UPDATE questions SET unit = '신경계', answer = '5' WHERE id = 534;
UPDATE questions SET unit = '신경계', answer = '5' WHERE id = 535;
UPDATE questions SET unit = '신경계', answer = '3' WHERE id = 536;
UPDATE questions SET unit = '신경계', answer = '2' WHERE id = 537;
UPDATE questions SET unit = '신경계', answer = '5' WHERE id = 538;
UPDATE questions SET unit = '신경계', answer = '4' WHERE id = 539;
UPDATE questions SET unit = '신경계', answer = '1' WHERE id = 540;
UPDATE questions SET unit = '신경계', answer = '4' WHERE id = 541;
UPDATE questions SET unit = '신경계', answer = '4' WHERE id = 542;
UPDATE questions SET unit = '신경계', answer = '3' WHERE id = 543;
UPDATE questions SET unit = '신경계', answer = '5' WHERE id = 544;
UPDATE questions SET unit = '신경계', answer = '4' WHERE id = 545;
UPDATE questions SET unit = '신경계', answer = '3' WHERE id = 546;
UPDATE questions SET unit = '신경계', answer = '5' WHERE id = 547;
UPDATE questions SET unit = '신경계', answer = '4' WHERE id = 548;
UPDATE questions SET unit = '신경계', answer = '2' WHERE id = 549;
UPDATE questions SET unit = '신경계', answer = '1' WHERE id = 550;
UPDATE questions SET unit = '신경계', answer = '5' WHERE id = 551;

-- [항상성 조절] 문제 241-300 (id 552-611)
UPDATE questions SET unit = '항상성 조절', answer = '2' WHERE id = 552;
UPDATE questions SET unit = '항상성 조절', answer = '4' WHERE id = 553;
UPDATE questions SET unit = '항상성 조절', answer = '2' WHERE id = 554;
UPDATE questions SET unit = '항상성 조절', answer = '3' WHERE id = 555;
UPDATE questions SET unit = '항상성 조절', answer = '5' WHERE id = 556;
UPDATE questions SET unit = '항상성 조절', answer = '5' WHERE id = 557;
UPDATE questions SET unit = '항상성 조절', answer = '1' WHERE id = 558;
UPDATE questions SET unit = '항상성 조절', answer = '5' WHERE id = 559;
UPDATE questions SET unit = '항상성 조절', answer = '1' WHERE id = 560;
UPDATE questions SET unit = '항상성 조절', answer = '4' WHERE id = 561;
UPDATE questions SET unit = '항상성 조절', answer = '4' WHERE id = 562;
UPDATE questions SET unit = '항상성 조절', answer = '3' WHERE id = 563;
UPDATE questions SET unit = '항상성 조절', answer = '1' WHERE id = 564;
UPDATE questions SET unit = '항상성 조절', answer = '4' WHERE id = 565;
UPDATE questions SET unit = '항상성 조절', answer = '2' WHERE id = 566;
UPDATE questions SET unit = '항상성 조절', answer = '2' WHERE id = 567;
UPDATE questions SET unit = '항상성 조절', answer = '5' WHERE id = 568;
UPDATE questions SET unit = '항상성 조절', answer = '4' WHERE id = 569;
UPDATE questions SET unit = '항상성 조절', answer = '5' WHERE id = 570;
UPDATE questions SET unit = '항상성 조절', answer = '4' WHERE id = 571;
UPDATE questions SET unit = '항상성 조절', answer = '4' WHERE id = 572;
UPDATE questions SET unit = '항상성 조절', answer = '3' WHERE id = 573;
UPDATE questions SET unit = '항상성 조절', answer = '2' WHERE id = 574;
UPDATE questions SET unit = '항상성 조절', answer = '5' WHERE id = 575;
UPDATE questions SET unit = '항상성 조절', answer = '5' WHERE id = 576;
UPDATE questions SET unit = '항상성 조절', answer = '2' WHERE id = 577;
UPDATE questions SET unit = '항상성 조절', answer = '5' WHERE id = 578;
UPDATE questions SET unit = '항상성 조절', answer = '5' WHERE id = 579;
UPDATE questions SET unit = '항상성 조절', answer = '5' WHERE id = 580;
UPDATE questions SET unit = '항상성 조절', answer = '2' WHERE id = 581;
UPDATE questions SET unit = '항상성 조절', answer = '4' WHERE id = 582;
UPDATE questions SET unit = '항상성 조절', answer = '5' WHERE id = 583;
UPDATE questions SET unit = '항상성 조절', answer = '4' WHERE id = 584;
UPDATE questions SET unit = '항상성 조절', answer = '5' WHERE id = 585;
UPDATE questions SET unit = '항상성 조절', answer = '3' WHERE id = 586;
UPDATE questions SET unit = '항상성 조절', answer = '3' WHERE id = 587;
UPDATE questions SET unit = '항상성 조절', answer = '1' WHERE id = 588;
UPDATE questions SET unit = '항상성 조절', answer = '2' WHERE id = 589;
UPDATE questions SET unit = '항상성 조절', answer = '4' WHERE id = 590;
UPDATE questions SET unit = '항상성 조절', answer = '2' WHERE id = 591;
UPDATE questions SET unit = '항상성 조절', answer = '3' WHERE id = 592;
UPDATE questions SET unit = '항상성 조절', answer = '2' WHERE id = 593;
UPDATE questions SET unit = '항상성 조절', answer = '5' WHERE id = 594;
UPDATE questions SET unit = '항상성 조절', answer = '4' WHERE id = 595;
UPDATE questions SET unit = '항상성 조절', answer = '5' WHERE id = 596;
UPDATE questions SET unit = '항상성 조절', answer = '2' WHERE id = 597;
UPDATE questions SET unit = '항상성 조절', answer = '5' WHERE id = 598;
UPDATE questions SET unit = '항상성 조절', answer = '2' WHERE id = 599;
UPDATE questions SET unit = '항상성 조절', answer = '4' WHERE id = 600;
UPDATE questions SET unit = '항상성 조절', answer = '3' WHERE id = 601;
UPDATE questions SET unit = '항상성 조절', answer = '5' WHERE id = 602;
UPDATE questions SET unit = '항상성 조절', answer = '4' WHERE id = 603;
UPDATE questions SET unit = '항상성 조절', answer = '1' WHERE id = 604;
UPDATE questions SET unit = '항상성 조절', answer = '5' WHERE id = 605;
UPDATE questions SET unit = '항상성 조절', answer = '5' WHERE id = 606;
UPDATE questions SET unit = '항상성 조절', answer = '3' WHERE id = 607;
UPDATE questions SET unit = '항상성 조절', answer = '4' WHERE id = 608;
UPDATE questions SET unit = '항상성 조절', answer = '2' WHERE id = 609;
UPDATE questions SET unit = '항상성 조절', answer = '3' WHERE id = 610;
UPDATE questions SET unit = '항상성 조절', answer = '3' WHERE id = 611;

-- [방어 작용] 문제 301-360 (id 612-671)
UPDATE questions SET unit = '방어 작용', answer = '1' WHERE id = 612;
UPDATE questions SET unit = '방어 작용', answer = '4' WHERE id = 613;
UPDATE questions SET unit = '방어 작용', answer = '4' WHERE id = 614;
UPDATE questions SET unit = '방어 작용', answer = '1' WHERE id = 615;
UPDATE questions SET unit = '방어 작용', answer = '1' WHERE id = 616;
UPDATE questions SET unit = '방어 작용', answer = '2' WHERE id = 617;
UPDATE questions SET unit = '방어 작용', answer = '5' WHERE id = 618;
UPDATE questions SET unit = '방어 작용', answer = '2' WHERE id = 619;
UPDATE questions SET unit = '방어 작용', answer = '4' WHERE id = 620;
UPDATE questions SET unit = '방어 작용', answer = '5' WHERE id = 621;
UPDATE questions SET unit = '방어 작용', answer = '1' WHERE id = 622;
UPDATE questions SET unit = '방어 작용', answer = '3' WHERE id = 623;
UPDATE questions SET unit = '방어 작용', answer = '2' WHERE id = 624;
UPDATE questions SET unit = '방어 작용', answer = '2' WHERE id = 625;
UPDATE questions SET unit = '방어 작용', answer = '2' WHERE id = 626;
UPDATE questions SET unit = '방어 작용', answer = '1' WHERE id = 627;
UPDATE questions SET unit = '방어 작용', answer = '2' WHERE id = 628;
UPDATE questions SET unit = '방어 작용', answer = '4' WHERE id = 629;
UPDATE questions SET unit = '방어 작용', answer = '3' WHERE id = 630;
UPDATE questions SET unit = '방어 작용', answer = '5' WHERE id = 631;
UPDATE questions SET unit = '방어 작용', answer = '4' WHERE id = 632;
UPDATE questions SET unit = '방어 작용', answer = '3' WHERE id = 633;
UPDATE questions SET unit = '방어 작용', answer = '3' WHERE id = 634;
UPDATE questions SET unit = '방어 작용', answer = '3' WHERE id = 635;
UPDATE questions SET unit = '방어 작용', answer = '2' WHERE id = 636;
UPDATE questions SET unit = '방어 작용', answer = '4' WHERE id = 637;
UPDATE questions SET unit = '방어 작용', answer = '1' WHERE id = 638;
UPDATE questions SET unit = '방어 작용', answer = '5' WHERE id = 639;
UPDATE questions SET unit = '방어 작용', answer = '3' WHERE id = 640;
UPDATE questions SET unit = '방어 작용', answer = '2' WHERE id = 641;
UPDATE questions SET unit = '방어 작용', answer = '2' WHERE id = 642;
UPDATE questions SET unit = '방어 작용', answer = '3' WHERE id = 643;
UPDATE questions SET unit = '방어 작용', answer = '4' WHERE id = 644;
UPDATE questions SET unit = '방어 작용', answer = '1' WHERE id = 645;
UPDATE questions SET unit = '방어 작용', answer = '1' WHERE id = 646;
UPDATE questions SET unit = '방어 작용', answer = '5' WHERE id = 647;
UPDATE questions SET unit = '방어 작용', answer = '1' WHERE id = 648;
UPDATE questions SET unit = '방어 작용', answer = '2' WHERE id = 649;
UPDATE questions SET unit = '방어 작용', answer = '3' WHERE id = 650;
UPDATE questions SET unit = '방어 작용', answer = '4' WHERE id = 651;
UPDATE questions SET unit = '방어 작용', answer = '4' WHERE id = 652;
UPDATE questions SET unit = '방어 작용', answer = '2' WHERE id = 653;
UPDATE questions SET unit = '방어 작용', answer = '5' WHERE id = 654;
UPDATE questions SET unit = '방어 작용', answer = '3' WHERE id = 655;
UPDATE questions SET unit = '방어 작용', answer = '3' WHERE id = 656;
UPDATE questions SET unit = '방어 작용', answer = '3' WHERE id = 657;
UPDATE questions SET unit = '방어 작용', answer = '5' WHERE id = 658;
UPDATE questions SET unit = '방어 작용', answer = '2' WHERE id = 659;
UPDATE questions SET unit = '방어 작용', answer = '5' WHERE id = 660;
UPDATE questions SET unit = '방어 작용', answer = '5' WHERE id = 661;
UPDATE questions SET unit = '방어 작용', answer = '4' WHERE id = 662;
UPDATE questions SET unit = '방어 작용', answer = '5' WHERE id = 663;
UPDATE questions SET unit = '방어 작용', answer = '2' WHERE id = 664;
UPDATE questions SET unit = '방어 작용', answer = '2' WHERE id = 665;
UPDATE questions SET unit = '방어 작용', answer = '2' WHERE id = 666;
UPDATE questions SET unit = '방어 작용', answer = '3' WHERE id = 667;
UPDATE questions SET unit = '방어 작용', answer = '5' WHERE id = 668;
UPDATE questions SET unit = '방어 작용', answer = '5' WHERE id = 669;
UPDATE questions SET unit = '방어 작용', answer = '2' WHERE id = 670;
UPDATE questions SET unit = '방어 작용', answer = '2' WHERE id = 671;

-- [염색체와 세포분열] 문제 361-420 (id 672-731)
UPDATE questions SET unit = '염색체와 세포분열', answer = '3' WHERE id = 672;
UPDATE questions SET unit = '염색체와 세포분열', answer = '1' WHERE id = 673;
UPDATE questions SET unit = '염색체와 세포분열', answer = '4' WHERE id = 674;
UPDATE questions SET unit = '염색체와 세포분열', answer = '3' WHERE id = 675;
UPDATE questions SET unit = '염색체와 세포분열', answer = '5' WHERE id = 676;
UPDATE questions SET unit = '염색체와 세포분열', answer = '3' WHERE id = 677;
UPDATE questions SET unit = '염색체와 세포분열', answer = '3' WHERE id = 678;
UPDATE questions SET unit = '염색체와 세포분열', answer = '5' WHERE id = 679;
UPDATE questions SET unit = '염색체와 세포분열', answer = '4' WHERE id = 680;
UPDATE questions SET unit = '염색체와 세포분열', answer = '3' WHERE id = 681;
UPDATE questions SET unit = '염색체와 세포분열', answer = '5' WHERE id = 682;
UPDATE questions SET unit = '염색체와 세포분열', answer = '5' WHERE id = 683;
UPDATE questions SET unit = '염색체와 세포분열', answer = '2' WHERE id = 684;
UPDATE questions SET unit = '염색체와 세포분열', answer = '1' WHERE id = 685;
UPDATE questions SET unit = '염색체와 세포분열', answer = '5' WHERE id = 686;
UPDATE questions SET unit = '염색체와 세포분열', answer = '4' WHERE id = 687;
UPDATE questions SET unit = '염색체와 세포분열', answer = '2' WHERE id = 688;
UPDATE questions SET unit = '염색체와 세포분열', answer = '2' WHERE id = 689;
UPDATE questions SET unit = '염색체와 세포분열', answer = '3' WHERE id = 690;
UPDATE questions SET unit = '염색체와 세포분열', answer = '5' WHERE id = 691;
UPDATE questions SET unit = '염색체와 세포분열', answer = '2' WHERE id = 692;
UPDATE questions SET unit = '염색체와 세포분열', answer = '2' WHERE id = 693;
UPDATE questions SET unit = '염색체와 세포분열', answer = '1' WHERE id = 694;
UPDATE questions SET unit = '염색체와 세포분열', answer = '3' WHERE id = 695;
UPDATE questions SET unit = '염색체와 세포분열', answer = '1' WHERE id = 696;
UPDATE questions SET unit = '염색체와 세포분열', answer = '5' WHERE id = 697;
UPDATE questions SET unit = '염색체와 세포분열', answer = '5' WHERE id = 698;
UPDATE questions SET unit = '염색체와 세포분열', answer = '5' WHERE id = 699;
UPDATE questions SET unit = '염색체와 세포분열', answer = '1' WHERE id = 700;
UPDATE questions SET unit = '염색체와 세포분열', answer = '2' WHERE id = 701;
UPDATE questions SET unit = '염색체와 세포분열', answer = '5' WHERE id = 702;
UPDATE questions SET unit = '염색체와 세포분열', answer = '4' WHERE id = 703;
UPDATE questions SET unit = '염색체와 세포분열', answer = '2' WHERE id = 704;
UPDATE questions SET unit = '염색체와 세포분열', answer = '4' WHERE id = 705;
UPDATE questions SET unit = '염색체와 세포분열', answer = '5' WHERE id = 706;
UPDATE questions SET unit = '염색체와 세포분열', answer = '2' WHERE id = 707;
UPDATE questions SET unit = '염색체와 세포분열', answer = '4' WHERE id = 708;
UPDATE questions SET unit = '염색체와 세포분열', answer = '3' WHERE id = 709;
UPDATE questions SET unit = '염색체와 세포분열', answer = '1' WHERE id = 710;
UPDATE questions SET unit = '염색체와 세포분열', answer = '3' WHERE id = 711;
UPDATE questions SET unit = '염색체와 세포분열', answer = '4' WHERE id = 712;
UPDATE questions SET unit = '염색체와 세포분열', answer = '2' WHERE id = 713;
UPDATE questions SET unit = '염색체와 세포분열', answer = '4' WHERE id = 714;
UPDATE questions SET unit = '염색체와 세포분열', answer = '3' WHERE id = 715;
UPDATE questions SET unit = '염색체와 세포분열', answer = '1' WHERE id = 716;
UPDATE questions SET unit = '염색체와 세포분열', answer = '5' WHERE id = 717;
UPDATE questions SET unit = '염색체와 세포분열', answer = '2' WHERE id = 718;
UPDATE questions SET unit = '염색체와 세포분열', answer = '2' WHERE id = 719;
UPDATE questions SET unit = '염색체와 세포분열', answer = '5' WHERE id = 720;
UPDATE questions SET unit = '염색체와 세포분열', answer = '2' WHERE id = 721;
UPDATE questions SET unit = '염색체와 세포분열', answer = '5' WHERE id = 722;
UPDATE questions SET unit = '염색체와 세포분열', answer = '5' WHERE id = 723;
UPDATE questions SET unit = '염색체와 세포분열', answer = '3' WHERE id = 724;
UPDATE questions SET unit = '염색체와 세포분열', answer = '1' WHERE id = 725;
UPDATE questions SET unit = '염색체와 세포분열', answer = '4' WHERE id = 726;
UPDATE questions SET unit = '염색체와 세포분열', answer = '5' WHERE id = 727;
UPDATE questions SET unit = '염색체와 세포분열', answer = '3' WHERE id = 728;
UPDATE questions SET unit = '염색체와 세포분열', answer = '2' WHERE id = 729;
UPDATE questions SET unit = '염색체와 세포분열', answer = '2' WHERE id = 730;
UPDATE questions SET unit = '염색체와 세포분열', answer = '5' WHERE id = 731;

-- [생물의 진화] 문제 421-447 (id 732-758)
UPDATE questions SET unit = '생물의 진화', answer = '5' WHERE id = 732;
UPDATE questions SET unit = '생물의 진화', answer = '5' WHERE id = 733;
UPDATE questions SET unit = '생물의 진화', answer = '4' WHERE id = 734;
UPDATE questions SET unit = '생물의 진화', answer = '4' WHERE id = 735;
UPDATE questions SET unit = '생물의 진화', answer = '2' WHERE id = 736;
UPDATE questions SET unit = '생물의 진화', answer = '4' WHERE id = 737;
UPDATE questions SET unit = '생물의 진화', answer = '1' WHERE id = 738;
UPDATE questions SET unit = '생물의 진화', answer = '4' WHERE id = 739;
UPDATE questions SET unit = '생물의 진화', answer = '5' WHERE id = 740;
UPDATE questions SET unit = '생물의 진화', answer = '3' WHERE id = 741;
UPDATE questions SET unit = '생물의 진화', answer = '4' WHERE id = 742;
UPDATE questions SET unit = '생물의 진화', answer = '5' WHERE id = 743;
UPDATE questions SET unit = '생물의 진화', answer = '2' WHERE id = 744;
UPDATE questions SET unit = '생물의 진화', answer = '3' WHERE id = 745;
UPDATE questions SET unit = '생물의 진화', answer = '5' WHERE id = 746;
UPDATE questions SET unit = '생물의 진화', answer = '5' WHERE id = 747;
UPDATE questions SET unit = '생물의 진화', answer = '5' WHERE id = 748;
UPDATE questions SET unit = '생물의 진화', answer = '2' WHERE id = 749;
UPDATE questions SET unit = '생물의 진화', answer = '2' WHERE id = 750;
UPDATE questions SET unit = '생물의 진화', answer = '3' WHERE id = 751;
UPDATE questions SET unit = '생물의 진화', answer = '4' WHERE id = 752;
UPDATE questions SET unit = '생물의 진화', answer = '1' WHERE id = 753;
UPDATE questions SET unit = '생물의 진화', answer = '5' WHERE id = 754;
UPDATE questions SET unit = '생물의 진화', answer = '5' WHERE id = 755;
UPDATE questions SET unit = '생물의 진화', answer = '3' WHERE id = 756;
UPDATE questions SET unit = '생물의 진화', answer = '3' WHERE id = 757;
UPDATE questions SET unit = '생물의 진화', answer = '1' WHERE id = 758;

-- 결과 확인
SELECT unit, COUNT(*) as count, MIN(id) as start_id, MAX(id) as end_id
FROM questions
WHERE category = '생명과학'
GROUP BY unit
ORDER BY MIN(id);
